### ISSUE TITLE
Name change for delete action

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/toki-hapi-bridge#5]
#### Context

The name for the `delete` action should be spelled out.  All other actions are spelled out except for this.

This change should be absorbed through `toki` as well.

**Comment by WesTyler** [comment]
A lot of libs with a `.delete` method use something like `del`, since `delete` is a reserved keyword in JS world. Like superagent, I think. 
Just food for thought :)

**Comment by lamchakchan** [comment]
Shouldn't be an issue in node.  Refer to [this](https://github.com/visionmedia/superagent/issues/605)

**Comment by dhinklexo** [comment]
Resolved
